import type { Platform, PlatformGroup } from "@/lib/types";

export const platformGroups: PlatformGroup[] = [
  { key: "civic", label: { vi: "Civic Tech", en: "Civic Tech" }, dotClass: "bg-red-600" },
  { key: "health", label: { vi: "Health & Parenting", en: "Health & Parenting" }, dotClass: "bg-sky-500" },
  { key: "legal-edu", label: { vi: "Legal Tech & Education", en: "Legal Tech & Education" }, dotClass: "bg-violet-500" },
  { key: "content-finance", label: { vi: "Content, Booking & Finance", en: "Content, Booking & Finance" }, dotClass: "bg-amber-500" },
];

export const platforms: Platform[] = [
  {
    slug: "nothue",
    name: "Nợ Thuế",
    domain: "nothue.com.vn",
    emoji: "📋",
    description: { vi: "Tra cứu dữ liệu nợ thuế công khai.", en: "Public tax-debt lookup." },
    status: "building",
    owners: ["VEA Tech"],
    group: "civic",
  },
  {
    slug: "tracuunothue",
    name: "Tra Cứu Nợ Thuế",
    domain: "tracuunothue.com",
    emoji: "🧾",
    description: { vi: "Công cụ tra cứu nợ thuế.", en: "Tax-debt lookup tool." },
    status: "building",
    owners: ["VEA Tech"],
    group: "civic",
  },
  {
    slug: "tracuuquyhoach",
    name: "Tra Cứu Quy Hoạch",
    domain: "tracuuquyhoach.com.vn",
    emoji: "🗺️",
    description: { vi: "Tra cứu thông tin quy hoạch.", en: "Planning information lookup." },
    status: "building",
    owners: ["VEA Tech"],
    group: "civic",
  },
  {
    slug: "danhbabacsi",
    name: "Danh Bạ Bác Sĩ",
    domain: "danhbabacsi.com.vn",
    emoji: "🏥",
    description: { vi: "Tìm kiếm bác sĩ theo chuyên khoa và khu vực.", en: "Find doctors by specialty and area." },
    status: "building",
    owners: ["VEA Tech"],
    group: "health",
  },
  {
    slug: "suaembe",
    name: "SuaEmbe",
    domain: "suaembe.com",
    emoji: "🍼",
    description: { vi: "Hệ sinh thái mẹ & bé.", en: "Mother and baby ecosystem." },
    status: "live",
    owners: ["VEA Tech · Retail"],
    group: "health",
  },
  {
    slug: "suacongthuc",
    name: "Sữa Công Thức",
    domain: "suacongthuc.com",
    emoji: "📐",
    description: { vi: "Thông tin và so sánh sữa công thức.", en: "Infant-formula information and comparison." },
    status: "building",
    owners: ["VEA Tech"],
    group: "health",
  },
  {
    slug: "danhbaluatsu",
    name: "Danh Bạ Luật Sư ĐNA",
    domain: "danhbaluatsu.asia",
    emoji: "⚖️",
    description: { vi: "Thư mục luật sư Đông Nam Á.", en: "Southeast Asian lawyer directory." },
    status: "live",
    owners: ["VEA Tech · Law"],
    group: "legal-edu",
  },
  {
    slug: "luatsutranhtung",
    name: "Luật Sư Tranh Tụng",
    domain: "luatsutranhtung.com",
    emoji: "🏛️",
    description: { vi: "Kết nối khách hàng với luật sư tranh tụng.", en: "Connect clients with litigation lawyers." },
    status: "building",
    owners: ["VEA Law · Tech"],
    group: "legal-edu",
  },
  {
    slug: "tienganhphaply",
    name: "Tiếng Anh Pháp Lý",
    domain: "tienganhphaply.com.vn",
    emoji: "📖",
    description: { vi: "Đào tạo tiếng Anh pháp lý.", en: "Legal-English education." },
    status: "building",
    owners: ["VEA Academy"],
    group: "legal-edu",
  },
  {
    slug: "truyenma",
    name: "Truyện Ma",
    domain: "truyenma.com.vn",
    emoji: "👻",
    description: { vi: "Nền tảng truyện ma và audio.", en: "Horror fiction and audio platform." },
    status: "building",
    owners: ["VEA Tech"],
    group: "content-finance",
  },
  {
    slug: "nightlife",
    name: "Nightlife",
    domain: "nightlife.com.vn",
    emoji: "🌃",
    description: { vi: "Bar, club, rooftop, đặt bàn và happy hour.", en: "Bars, clubs, rooftops, reservations and happy hour." },
    status: "live",
    owners: ["VEA Tech · Retail"],
    group: "content-finance",
  },
  {
    slug: "sancrypto",
    name: "SanCrypto",
    domain: "sancrypto.com.vn",
    emoji: "₿",
    description: { vi: "Thông tin và dữ liệu thị trường crypto.", en: "Crypto market information and data." },
    status: "building",
    owners: ["VEA Tech"],
    group: "content-finance",
  },
  {
    slug: "bookinglivestream",
    name: "Booking Livestream",
    domain: "bookinglivestream.com",
    emoji: "▶️",
    description: { vi: "Booking host livestream bán hàng.", en: "Booking for livestream selling hosts." },
    status: "building",
    owners: ["VEA Media"],
    group: "content-finance",
  },
  {
    slug: "bookingmodel",
    name: "Booking Model",
    domain: "bookingmodel.com",
    emoji: "🎭",
    description: { vi: "Booking người mẫu và dancer cho sự kiện.", en: "Book models and dancers for events." },
    status: "building",
    owners: ["VEA Media"],
    group: "content-finance",
  },
];

export function platformsByGroup(groupKey: string): Platform[] {
  return platforms.filter((platform) => platform.group === groupKey);
}
